name: Build and Depoly Application

on:
  push:
    branches:
      - main
  
jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.LINA_DOCKER_USERNAME }}
          password: ${{ secrets.LINA_DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.LINA_DOCKER_USERNAME }}/SMHI_API_KEY_LINA:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.LINA_DOCKER_USERNAME }}/SMHI_API_KEY_LINA:latest

  deploy_to_azure:
    runs-on: ubuntu-latest
    needs: build_docker_image

    steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_NAME }}
        publish-profile: ${{ secrets.AZURE_PASSWORD }}
        images: ${{ secrets.LINA_DOCKER_USERNAME }}/SMHI_API_KEY_LINA:latest
