name: thomas-pipeline

on:
  workflow_dispatch:
    inputs:
      log_errors:
        description: "Log errors if tests fail"
        required: true
        default: "false"

env:
  SMHI_API_KEY: ${{ secrets.SMHI_API_KEY }}
  DOCKER_IMAGE_NAME: thomaslaene/weather-app

jobs:

  run_tests:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Unit Tests
        run: pytest tests/unit

      - name: Run Integration Tests
        run: pytest tests/integration


  build_and_push_docker_DeployGCP:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: run_tests  

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.THOMAS_DOCKER_USERNAME }}
          password: ${{ secrets.THOMAS_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY_FILE }}
      
      - name: Configure Docker to use gcloud as a credential helper
        run: |
         gcloud auth configure-docker

      - name: Tag and push to Google Container Registry
        run: |
         docker tag ${{ secrets.THOMAS_DOCKER_USERNAME }}/weather-app:${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/weather-app:${{ github.sha }}
         docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/weather-app:${{ github.sha }}

      - name: Deploy to Google Cloud Run
        run: |
         gcloud run deploy weather-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/weather-app:${{ github.sha }} \
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated
